### ISSUE TITLE
add Babylon to OP rollup chain configs

### ISSUE THREAD

**Issue by parketh** [babylonchain/optimism#12]
## Summary

Babylon configs (chain type and CW finality gadget contract address) are currently [hardcoded](https://github.com/babylonchain/optimism/blob/feat/babylon-rfc/op-node/rollup/finality/finalizer.go#L170) in the engine queue.

We should make these params part of the rollup configs and dynamically import them from the engine queue.

## Todos

- [ ] Add Babylon chain configs to `.envrc`
- [ ] Update config script to include new params
- [ ] Set chain configs on deployment
- [ ] Replace hardcoded values with configs in engine queue

**Comment by bap2pecs** [comment]
anything remaining here?
